//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EJBApplicationServiceServiceSoapBinding", Namespace="http://impl.business.sdi.uo/")]
public partial class EJBApplicationServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback listaApuntadosPromotorOperationCompleted;
    
    private System.Threading.SendOrPostCallback apuntarseViajeOperationCompleted;
    
    private System.Threading.SendOrPostCallback getApplicationOperationCompleted;
    
    private System.Threading.SendOrPostCallback aceptarUsuarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback listaApuntadosUsuarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback desapuntarseViajeOperationCompleted;
    
    private System.Threading.SendOrPostCallback cancelarUsuarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback peticionesParaUnViajeOperationCompleted;
    
    /// <remarks/>
    public EJBApplicationServiceService() {
        this.Url = "http://Vodkaneitor:8280/sdi3-40.EJB/ApplicationService";
    }
    
    /// <remarks/>
    public event listaApuntadosPromotorCompletedEventHandler listaApuntadosPromotorCompleted;
    
    /// <remarks/>
    public event apuntarseViajeCompletedEventHandler apuntarseViajeCompleted;
    
    /// <remarks/>
    public event getApplicationCompletedEventHandler getApplicationCompleted;
    
    /// <remarks/>
    public event aceptarUsuarioCompletedEventHandler aceptarUsuarioCompleted;
    
    /// <remarks/>
    public event listaApuntadosUsuarioCompletedEventHandler listaApuntadosUsuarioCompleted;
    
    /// <remarks/>
    public event desapuntarseViajeCompletedEventHandler desapuntarseViajeCompleted;
    
    /// <remarks/>
    public event cancelarUsuarioCompletedEventHandler cancelarUsuarioCompleted;
    
    /// <remarks/>
    public event peticionesParaUnViajeCompletedEventHandler peticionesParaUnViajeCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public listaApuntados[] listaApuntadosPromotor([System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip[] arg0) {
        object[] results = this.Invoke("listaApuntadosPromotor", new object[] {
                    arg0});
        return ((listaApuntados[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistaApuntadosPromotor(trip[] arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listaApuntadosPromotor", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public listaApuntados[] EndlistaApuntadosPromotor(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((listaApuntados[])(results[0]));
    }
    
    /// <remarks/>
    public void listaApuntadosPromotorAsync(trip[] arg0) {
        this.listaApuntadosPromotorAsync(arg0, null);
    }
    
    /// <remarks/>
    public void listaApuntadosPromotorAsync(trip[] arg0, object userState) {
        if ((this.listaApuntadosPromotorOperationCompleted == null)) {
            this.listaApuntadosPromotorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaApuntadosPromotorOperationCompleted);
        }
        this.InvokeAsync("listaApuntadosPromotor", new object[] {
                    arg0}, this.listaApuntadosPromotorOperationCompleted, userState);
    }
    
    private void OnlistaApuntadosPromotorOperationCompleted(object arg) {
        if ((this.listaApuntadosPromotorCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listaApuntadosPromotorCompleted(this, new listaApuntadosPromotorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void apuntarseViaje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] listaApuntados arg0) {
        this.Invoke("apuntarseViaje", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginapuntarseViaje(listaApuntados arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("apuntarseViaje", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndapuntarseViaje(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void apuntarseViajeAsync(listaApuntados arg0) {
        this.apuntarseViajeAsync(arg0, null);
    }
    
    /// <remarks/>
    public void apuntarseViajeAsync(listaApuntados arg0, object userState) {
        if ((this.apuntarseViajeOperationCompleted == null)) {
            this.apuntarseViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnapuntarseViajeOperationCompleted);
        }
        this.InvokeAsync("apuntarseViaje", new object[] {
                    arg0}, this.apuntarseViajeOperationCompleted, userState);
    }
    
    private void OnapuntarseViajeOperationCompleted(object arg) {
        if ((this.apuntarseViajeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.apuntarseViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public application[] getApplication() {
        object[] results = this.Invoke("getApplication", new object[0]);
        return ((application[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetApplication(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getApplication", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public application[] EndgetApplication(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((application[])(results[0]));
    }
    
    /// <remarks/>
    public void getApplicationAsync() {
        this.getApplicationAsync(null);
    }
    
    /// <remarks/>
    public void getApplicationAsync(object userState) {
        if ((this.getApplicationOperationCompleted == null)) {
            this.getApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetApplicationOperationCompleted);
        }
        this.InvokeAsync("getApplication", new object[0], this.getApplicationOperationCompleted, userState);
    }
    
    private void OngetApplicationOperationCompleted(object arg) {
        if ((this.getApplicationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getApplicationCompleted(this, new getApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public seat aceptarUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] listaApuntados arg0) {
        object[] results = this.Invoke("aceptarUsuario", new object[] {
                    arg0});
        return ((seat)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaceptarUsuario(listaApuntados arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("aceptarUsuario", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public seat EndaceptarUsuario(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((seat)(results[0]));
    }
    
    /// <remarks/>
    public void aceptarUsuarioAsync(listaApuntados arg0) {
        this.aceptarUsuarioAsync(arg0, null);
    }
    
    /// <remarks/>
    public void aceptarUsuarioAsync(listaApuntados arg0, object userState) {
        if ((this.aceptarUsuarioOperationCompleted == null)) {
            this.aceptarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaceptarUsuarioOperationCompleted);
        }
        this.InvokeAsync("aceptarUsuario", new object[] {
                    arg0}, this.aceptarUsuarioOperationCompleted, userState);
    }
    
    private void OnaceptarUsuarioOperationCompleted(object arg) {
        if ((this.aceptarUsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.aceptarUsuarioCompleted(this, new aceptarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public listaApuntados[] listaApuntadosUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg0) {
        object[] results = this.Invoke("listaApuntadosUsuario", new object[] {
                    arg0});
        return ((listaApuntados[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistaApuntadosUsuario(user arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listaApuntadosUsuario", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public listaApuntados[] EndlistaApuntadosUsuario(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((listaApuntados[])(results[0]));
    }
    
    /// <remarks/>
    public void listaApuntadosUsuarioAsync(user arg0) {
        this.listaApuntadosUsuarioAsync(arg0, null);
    }
    
    /// <remarks/>
    public void listaApuntadosUsuarioAsync(user arg0, object userState) {
        if ((this.listaApuntadosUsuarioOperationCompleted == null)) {
            this.listaApuntadosUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaApuntadosUsuarioOperationCompleted);
        }
        this.InvokeAsync("listaApuntadosUsuario", new object[] {
                    arg0}, this.listaApuntadosUsuarioOperationCompleted, userState);
    }
    
    private void OnlistaApuntadosUsuarioOperationCompleted(object arg) {
        if ((this.listaApuntadosUsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listaApuntadosUsuarioCompleted(this, new listaApuntadosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int desapuntarseViaje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] listaApuntados arg0) {
        object[] results = this.Invoke("desapuntarseViaje", new object[] {
                    arg0});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindesapuntarseViaje(listaApuntados arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("desapuntarseViaje", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EnddesapuntarseViaje(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void desapuntarseViajeAsync(listaApuntados arg0) {
        this.desapuntarseViajeAsync(arg0, null);
    }
    
    /// <remarks/>
    public void desapuntarseViajeAsync(listaApuntados arg0, object userState) {
        if ((this.desapuntarseViajeOperationCompleted == null)) {
            this.desapuntarseViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndesapuntarseViajeOperationCompleted);
        }
        this.InvokeAsync("desapuntarseViaje", new object[] {
                    arg0}, this.desapuntarseViajeOperationCompleted, userState);
    }
    
    private void OndesapuntarseViajeOperationCompleted(object arg) {
        if ((this.desapuntarseViajeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.desapuntarseViajeCompleted(this, new desapuntarseViajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public seat cancelarUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] listaApuntados arg0) {
        object[] results = this.Invoke("cancelarUsuario", new object[] {
                    arg0});
        return ((seat)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincancelarUsuario(listaApuntados arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("cancelarUsuario", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public seat EndcancelarUsuario(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((seat)(results[0]));
    }
    
    /// <remarks/>
    public void cancelarUsuarioAsync(listaApuntados arg0) {
        this.cancelarUsuarioAsync(arg0, null);
    }
    
    /// <remarks/>
    public void cancelarUsuarioAsync(listaApuntados arg0, object userState) {
        if ((this.cancelarUsuarioOperationCompleted == null)) {
            this.cancelarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarUsuarioOperationCompleted);
        }
        this.InvokeAsync("cancelarUsuario", new object[] {
                    arg0}, this.cancelarUsuarioOperationCompleted, userState);
    }
    
    private void OncancelarUsuarioOperationCompleted(object arg) {
        if ((this.cancelarUsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.cancelarUsuarioCompleted(this, new cancelarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public listaApuntados[] peticionesParaUnViaje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0) {
        object[] results = this.Invoke("peticionesParaUnViaje", new object[] {
                    arg0});
        return ((listaApuntados[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginpeticionesParaUnViaje(trip arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("peticionesParaUnViaje", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public listaApuntados[] EndpeticionesParaUnViaje(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((listaApuntados[])(results[0]));
    }
    
    /// <remarks/>
    public void peticionesParaUnViajeAsync(trip arg0) {
        this.peticionesParaUnViajeAsync(arg0, null);
    }
    
    /// <remarks/>
    public void peticionesParaUnViajeAsync(trip arg0, object userState) {
        if ((this.peticionesParaUnViajeOperationCompleted == null)) {
            this.peticionesParaUnViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpeticionesParaUnViajeOperationCompleted);
        }
        this.InvokeAsync("peticionesParaUnViaje", new object[] {
                    arg0}, this.peticionesParaUnViajeOperationCompleted, userState);
    }
    
    private void OnpeticionesParaUnViajeOperationCompleted(object arg) {
        if ((this.peticionesParaUnViajeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.peticionesParaUnViajeCompleted(this, new peticionesParaUnViajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class application {
    
    private long tripIdField;
    
    private bool tripIdFieldSpecified;
    
    private long userIdField;
    
    private bool userIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long tripId {
        get {
            return this.tripIdField;
        }
        set {
            this.tripIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tripIdSpecified {
        get {
            return this.tripIdFieldSpecified;
        }
        set {
            this.tripIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long userId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userIdSpecified {
        get {
            return this.userIdFieldSpecified;
        }
        set {
            this.userIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class seat {
    
    private string commentField;
    
    private seatStatus statusField;
    
    private bool statusFieldSpecified;
    
    private long tripIdField;
    
    private bool tripIdFieldSpecified;
    
    private long userIdField;
    
    private bool userIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public seatStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long tripId {
        get {
            return this.tripIdField;
        }
        set {
            this.tripIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tripIdSpecified {
        get {
            return this.tripIdFieldSpecified;
        }
        set {
            this.tripIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long userId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userIdSpecified {
        get {
            return this.userIdFieldSpecified;
        }
        set {
            this.userIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public enum seatStatus {
    
    /// <remarks/>
    ACCEPTED,
    
    /// <remarks/>
    EXCLUDED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class listaApuntados {
    
    private seat asientoField;
    
    private peticionEstado relacionViajeField;
    
    private bool relacionViajeFieldSpecified;
    
    private user usuarioField;
    
    private trip viajeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public seat asiento {
        get {
            return this.asientoField;
        }
        set {
            this.asientoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public peticionEstado relacionViaje {
        get {
            return this.relacionViajeField;
        }
        set {
            this.relacionViajeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool relacionViajeSpecified {
        get {
            return this.relacionViajeFieldSpecified;
        }
        set {
            this.relacionViajeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user usuario {
        get {
            return this.usuarioField;
        }
        set {
            this.usuarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip viaje {
        get {
            return this.viajeField;
        }
        set {
            this.viajeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public enum peticionEstado {
    
    /// <remarks/>
    ACCEPTED,
    
    /// <remarks/>
    EXCLUDED,
    
    /// <remarks/>
    PENDANT,
    
    /// <remarks/>
    PROMOTER,
    
    /// <remarks/>
    NO_SEAT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void listaApuntadosPromotorCompletedEventHandler(object sender, listaApuntadosPromotorCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listaApuntadosPromotorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listaApuntadosPromotorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public listaApuntados[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((listaApuntados[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void apuntarseViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void getApplicationCompletedEventHandler(object sender, getApplicationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public application[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((application[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void aceptarUsuarioCompletedEventHandler(object sender, aceptarUsuarioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class aceptarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal aceptarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public seat Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((seat)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void listaApuntadosUsuarioCompletedEventHandler(object sender, listaApuntadosUsuarioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listaApuntadosUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listaApuntadosUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public listaApuntados[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((listaApuntados[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void desapuntarseViajeCompletedEventHandler(object sender, desapuntarseViajeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class desapuntarseViajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal desapuntarseViajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void cancelarUsuarioCompletedEventHandler(object sender, cancelarUsuarioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class cancelarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal cancelarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public seat Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((seat)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void peticionesParaUnViajeCompletedEventHandler(object sender, peticionesParaUnViajeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class peticionesParaUnViajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal peticionesParaUnViajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public listaApuntados[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((listaApuntados[])(this.results[0]));
        }
    }
}
