//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EJBRatingServiceServiceSoapBinding", Namespace="http://impl.business.sdi.uo/")]
public partial class EJBRatingServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback listarRatingsOperationCompleted;
    
    private System.Threading.SendOrPostCallback listarComentariosOperationCompleted;
    
    private System.Threading.SendOrPostCallback eliminarComentariosOperationCompleted;
    
    /// <remarks/>
    public EJBRatingServiceService() {
        this.Url = "http://Vodkaneitor:8280/sdi3-40.EJB/RatingService";
    }
    
    /// <remarks/>
    public event listarRatingsCompletedEventHandler listarRatingsCompleted;
    
    /// <remarks/>
    public event listarComentariosCompletedEventHandler listarComentariosCompleted;
    
    /// <remarks/>
    public event eliminarComentariosCompletedEventHandler eliminarComentariosCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rating[] listarRatings() {
        object[] results = this.Invoke("listarRatings", new object[0]);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistarRatings(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listarRatings", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public rating[] EndlistarRatings(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public void listarRatingsAsync() {
        this.listarRatingsAsync(null);
    }
    
    /// <remarks/>
    public void listarRatingsAsync(object userState) {
        if ((this.listarRatingsOperationCompleted == null)) {
            this.listarRatingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarRatingsOperationCompleted);
        }
        this.InvokeAsync("listarRatings", new object[0], this.listarRatingsOperationCompleted, userState);
    }
    
    private void OnlistarRatingsOperationCompleted(object arg) {
        if ((this.listarRatingsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listarRatingsCompleted(this, new listarRatingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rating[] listarComentarios([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0) {
        object[] results = this.Invoke("listarComentarios", new object[] {
                    arg0});
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistarComentarios(trip arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listarComentarios", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public rating[] EndlistarComentarios(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public void listarComentariosAsync(trip arg0) {
        this.listarComentariosAsync(arg0, null);
    }
    
    /// <remarks/>
    public void listarComentariosAsync(trip arg0, object userState) {
        if ((this.listarComentariosOperationCompleted == null)) {
            this.listarComentariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarComentariosOperationCompleted);
        }
        this.InvokeAsync("listarComentarios", new object[] {
                    arg0}, this.listarComentariosOperationCompleted, userState);
    }
    
    private void OnlistarComentariosOperationCompleted(object arg) {
        if ((this.listarComentariosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listarComentariosCompleted(this, new listarComentariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void eliminarComentarios([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("eliminarComentarios", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegineliminarComentarios(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("eliminarComentarios", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndeliminarComentarios(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void eliminarComentariosAsync(long arg0, bool arg0Specified) {
        this.eliminarComentariosAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void eliminarComentariosAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.eliminarComentariosOperationCompleted == null)) {
            this.eliminarComentariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarComentariosOperationCompleted);
        }
        this.InvokeAsync("eliminarComentarios", new object[] {
                    arg0,
                    arg0Specified}, this.eliminarComentariosOperationCompleted, userState);
    }
    
    private void OneliminarComentariosOperationCompleted(object arg) {
        if ((this.eliminarComentariosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.eliminarComentariosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class rating {
    
    private string commentField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private long seatAboutTripIdField;
    
    private bool seatAboutTripIdFieldSpecified;
    
    private long seatAboutUserIdField;
    
    private bool seatAboutUserIdFieldSpecified;
    
    private long seatFromTripIdField;
    
    private bool seatFromTripIdFieldSpecified;
    
    private long seatFromUserIdField;
    
    private bool seatFromUserIdFieldSpecified;
    
    private int valueField;
    
    private bool valueFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatAboutTripId {
        get {
            return this.seatAboutTripIdField;
        }
        set {
            this.seatAboutTripIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatAboutTripIdSpecified {
        get {
            return this.seatAboutTripIdFieldSpecified;
        }
        set {
            this.seatAboutTripIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatAboutUserId {
        get {
            return this.seatAboutUserIdField;
        }
        set {
            this.seatAboutUserIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatAboutUserIdSpecified {
        get {
            return this.seatAboutUserIdFieldSpecified;
        }
        set {
            this.seatAboutUserIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatFromTripId {
        get {
            return this.seatFromTripIdField;
        }
        set {
            this.seatFromTripIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatFromTripIdSpecified {
        get {
            return this.seatFromTripIdFieldSpecified;
        }
        set {
            this.seatFromTripIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatFromUserId {
        get {
            return this.seatFromUserIdField;
        }
        set {
            this.seatFromUserIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatFromUserIdSpecified {
        get {
            return this.seatFromUserIdFieldSpecified;
        }
        set {
            this.seatFromUserIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueSpecified {
        get {
            return this.valueFieldSpecified;
        }
        set {
            this.valueFieldSpecified = value;
        }
    }
}
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void listarRatingsCompletedEventHandler(object sender, listarRatingsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listarRatingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listarRatingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public rating[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((rating[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void listarComentariosCompletedEventHandler(object sender, listarComentariosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listarComentariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listarComentariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public rating[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((rating[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void eliminarComentariosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
