//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EJBTripServiceServiceSoapBinding", Namespace="http://impl.business.sdi.uo/")]
public partial class EJBTripServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback creaViajeOperationCompleted;
    
    private System.Threading.SendOrPostCallback iniciaViajeOperationCompleted;
    
    private System.Threading.SendOrPostCallback buscarViajeOperationCompleted;
    
    private System.Threading.SendOrPostCallback actualizaViajeIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback listarViajesOperationCompleted;
    
    private System.Threading.SendOrPostCallback listaViajePromotorOperationCompleted;
    
    private System.Threading.SendOrPostCallback actualizarViajeOperationCompleted;
    
    private System.Threading.SendOrPostCallback listarViajesUltimoMesOperationCompleted;
    
    /// <remarks/>
    public EJBTripServiceService() {
        this.Url = "http://Vodkaneitor:8280/sdi3-40.EJB/TripService";
    }
    
    /// <remarks/>
    public event creaViajeCompletedEventHandler creaViajeCompleted;
    
    /// <remarks/>
    public event iniciaViajeCompletedEventHandler iniciaViajeCompleted;
    
    /// <remarks/>
    public event buscarViajeCompletedEventHandler buscarViajeCompleted;
    
    /// <remarks/>
    public event actualizaViajeIdCompletedEventHandler actualizaViajeIdCompleted;
    
    /// <remarks/>
    public event listarViajesCompletedEventHandler listarViajesCompleted;
    
    /// <remarks/>
    public event listaViajePromotorCompletedEventHandler listaViajePromotorCompleted;
    
    /// <remarks/>
    public event actualizarViajeCompletedEventHandler actualizarViajeCompleted;
    
    /// <remarks/>
    public event listarViajesUltimoMesCompletedEventHandler listarViajesUltimoMesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void creaViaje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg1) {
        this.Invoke("creaViaje", new object[] {
                    arg0,
                    arg1});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreaViaje(trip arg0, user arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("creaViaje", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndcreaViaje(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void creaViajeAsync(trip arg0, user arg1) {
        this.creaViajeAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void creaViajeAsync(trip arg0, user arg1, object userState) {
        if ((this.creaViajeOperationCompleted == null)) {
            this.creaViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreaViajeOperationCompleted);
        }
        this.InvokeAsync("creaViaje", new object[] {
                    arg0,
                    arg1}, this.creaViajeOperationCompleted, userState);
    }
    
    private void OncreaViajeOperationCompleted(object arg) {
        if ((this.creaViajeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.creaViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip iniciaViaje() {
        object[] results = this.Invoke("iniciaViaje", new object[0]);
        return ((trip)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegininiciaViaje(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("iniciaViaje", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public trip EndiniciaViaje(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip)(results[0]));
    }
    
    /// <remarks/>
    public void iniciaViajeAsync() {
        this.iniciaViajeAsync(null);
    }
    
    /// <remarks/>
    public void iniciaViajeAsync(object userState) {
        if ((this.iniciaViajeOperationCompleted == null)) {
            this.iniciaViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OniniciaViajeOperationCompleted);
        }
        this.InvokeAsync("iniciaViaje", new object[0], this.iniciaViajeOperationCompleted, userState);
    }
    
    private void OniniciaViajeOperationCompleted(object arg) {
        if ((this.iniciaViajeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.iniciaViajeCompleted(this, new iniciaViajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip buscarViaje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("buscarViaje", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuscarViaje(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buscarViaje", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip EndbuscarViaje(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip)(results[0]));
    }
    
    /// <remarks/>
    public void buscarViajeAsync(long arg0, bool arg0Specified) {
        this.buscarViajeAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void buscarViajeAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.buscarViajeOperationCompleted == null)) {
            this.buscarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarViajeOperationCompleted);
        }
        this.InvokeAsync("buscarViaje", new object[] {
                    arg0,
                    arg0Specified}, this.buscarViajeOperationCompleted, userState);
    }
    
    private void OnbuscarViajeOperationCompleted(object arg) {
        if ((this.buscarViajeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buscarViajeCompleted(this, new buscarViajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void actualizaViajeId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("actualizaViajeId", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginactualizaViajeId(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("actualizaViajeId", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndactualizaViajeId(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void actualizaViajeIdAsync(long arg0, bool arg0Specified) {
        this.actualizaViajeIdAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void actualizaViajeIdAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.actualizaViajeIdOperationCompleted == null)) {
            this.actualizaViajeIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizaViajeIdOperationCompleted);
        }
        this.InvokeAsync("actualizaViajeId", new object[] {
                    arg0,
                    arg0Specified}, this.actualizaViajeIdOperationCompleted, userState);
    }
    
    private void OnactualizaViajeIdOperationCompleted(object arg) {
        if ((this.actualizaViajeIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.actualizaViajeIdCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] listarViajes() {
        object[] results = this.Invoke("listarViajes", new object[0]);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistarViajes(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listarViajes", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndlistarViajes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void listarViajesAsync() {
        this.listarViajesAsync(null);
    }
    
    /// <remarks/>
    public void listarViajesAsync(object userState) {
        if ((this.listarViajesOperationCompleted == null)) {
            this.listarViajesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarViajesOperationCompleted);
        }
        this.InvokeAsync("listarViajes", new object[0], this.listarViajesOperationCompleted, userState);
    }
    
    private void OnlistarViajesOperationCompleted(object arg) {
        if ((this.listarViajesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listarViajesCompleted(this, new listarViajesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] listaViajePromotor([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("listaViajePromotor", new object[] {
                    arg0,
                    arg0Specified});
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistaViajePromotor(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listaViajePromotor", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndlistaViajePromotor(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void listaViajePromotorAsync(long arg0, bool arg0Specified) {
        this.listaViajePromotorAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void listaViajePromotorAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.listaViajePromotorOperationCompleted == null)) {
            this.listaViajePromotorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaViajePromotorOperationCompleted);
        }
        this.InvokeAsync("listaViajePromotor", new object[] {
                    arg0,
                    arg0Specified}, this.listaViajePromotorOperationCompleted, userState);
    }
    
    private void OnlistaViajePromotorOperationCompleted(object arg) {
        if ((this.listaViajePromotorCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listaViajePromotorCompleted(this, new listaViajePromotorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void actualizarViaje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trip arg0) {
        this.Invoke("actualizarViaje", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginactualizarViaje(trip arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("actualizarViaje", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndactualizarViaje(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void actualizarViajeAsync(trip arg0) {
        this.actualizarViajeAsync(arg0, null);
    }
    
    /// <remarks/>
    public void actualizarViajeAsync(trip arg0, object userState) {
        if ((this.actualizarViajeOperationCompleted == null)) {
            this.actualizarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarViajeOperationCompleted);
        }
        this.InvokeAsync("actualizarViaje", new object[] {
                    arg0}, this.actualizarViajeOperationCompleted, userState);
    }
    
    private void OnactualizarViajeOperationCompleted(object arg) {
        if ((this.actualizarViajeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.actualizarViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trip[] listarViajesUltimoMes() {
        object[] results = this.Invoke("listarViajesUltimoMes", new object[0]);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistarViajesUltimoMes(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listarViajesUltimoMes", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public trip[] EndlistarViajesUltimoMes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((trip[])(results[0]));
    }
    
    /// <remarks/>
    public void listarViajesUltimoMesAsync() {
        this.listarViajesUltimoMesAsync(null);
    }
    
    /// <remarks/>
    public void listarViajesUltimoMesAsync(object userState) {
        if ((this.listarViajesUltimoMesOperationCompleted == null)) {
            this.listarViajesUltimoMesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarViajesUltimoMesOperationCompleted);
        }
        this.InvokeAsync("listarViajesUltimoMes", new object[0], this.listarViajesUltimoMesOperationCompleted, userState);
    }
    
    private void OnlistarViajesUltimoMesOperationCompleted(object arg) {
        if ((this.listarViajesUltimoMesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listarViajesUltimoMesCompleted(this, new listarViajesUltimoMesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class trip {
    
    private System.DateTime arrivalDateField;
    
    private bool arrivalDateFieldSpecified;
    
    private int availablePaxField;
    
    private bool availablePaxFieldSpecified;
    
    private System.DateTime closingDateField;
    
    private bool closingDateFieldSpecified;
    
    private string commentsField;
    
    private addressPoint departureField;
    
    private System.DateTime departureDateField;
    
    private bool departureDateFieldSpecified;
    
    private addressPoint destinationField;
    
    private double estimatedCostField;
    
    private bool estimatedCostFieldSpecified;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private int maxPaxField;
    
    private bool maxPaxFieldSpecified;
    
    private long promoterIdField;
    
    private bool promoterIdFieldSpecified;
    
    private tripStatus statusField;
    
    private bool statusFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime arrivalDate {
        get {
            return this.arrivalDateField;
        }
        set {
            this.arrivalDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool arrivalDateSpecified {
        get {
            return this.arrivalDateFieldSpecified;
        }
        set {
            this.arrivalDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int availablePax {
        get {
            return this.availablePaxField;
        }
        set {
            this.availablePaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool availablePaxSpecified {
        get {
            return this.availablePaxFieldSpecified;
        }
        set {
            this.availablePaxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime closingDate {
        get {
            return this.closingDateField;
        }
        set {
            this.closingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool closingDateSpecified {
        get {
            return this.closingDateFieldSpecified;
        }
        set {
            this.closingDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public addressPoint departure {
        get {
            return this.departureField;
        }
        set {
            this.departureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime departureDate {
        get {
            return this.departureDateField;
        }
        set {
            this.departureDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool departureDateSpecified {
        get {
            return this.departureDateFieldSpecified;
        }
        set {
            this.departureDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public addressPoint destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double estimatedCost {
        get {
            return this.estimatedCostField;
        }
        set {
            this.estimatedCostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool estimatedCostSpecified {
        get {
            return this.estimatedCostFieldSpecified;
        }
        set {
            this.estimatedCostFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int maxPax {
        get {
            return this.maxPaxField;
        }
        set {
            this.maxPaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxPaxSpecified {
        get {
            return this.maxPaxFieldSpecified;
        }
        set {
            this.maxPaxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long promoterId {
        get {
            return this.promoterIdField;
        }
        set {
            this.promoterIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool promoterIdSpecified {
        get {
            return this.promoterIdFieldSpecified;
        }
        set {
            this.promoterIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public tripStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class addressPoint {
    
    private string addressField;
    
    private string cityField;
    
    private string countryField;
    
    private string stateField;
    
    private waypoint waypointField;
    
    private string zipCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public waypoint waypoint {
        get {
            return this.waypointField;
        }
        set {
            this.waypointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string zipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class waypoint {
    
    private double latField;
    
    private bool latFieldSpecified;
    
    private double lonField;
    
    private bool lonFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double lat {
        get {
            return this.latField;
        }
        set {
            this.latField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latSpecified {
        get {
            return this.latFieldSpecified;
        }
        set {
            this.latFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double lon {
        get {
            return this.lonField;
        }
        set {
            this.lonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lonSpecified {
        get {
            return this.lonFieldSpecified;
        }
        set {
            this.lonFieldSpecified = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public enum tripStatus {
    
    /// <remarks/>
    OPEN,
    
    /// <remarks/>
    CLOSED,
    
    /// <remarks/>
    CANCELLED,
    
    /// <remarks/>
    DONE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void creaViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void iniciaViajeCompletedEventHandler(object sender, iniciaViajeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class iniciaViajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal iniciaViajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void buscarViajeCompletedEventHandler(object sender, buscarViajeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buscarViajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buscarViajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void actualizaViajeIdCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void listarViajesCompletedEventHandler(object sender, listarViajesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listarViajesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listarViajesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void listaViajePromotorCompletedEventHandler(object sender, listaViajePromotorCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listaViajePromotorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listaViajePromotorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void actualizarViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void listarViajesUltimoMesCompletedEventHandler(object sender, listarViajesUltimoMesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listarViajesUltimoMesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listarViajesUltimoMesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public trip[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((trip[])(this.results[0]));
        }
    }
}
