//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EJBUserServiceServiceSoapBinding", Namespace="http://impl.business.sdi.uo/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Exception))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(buscaUsuarioResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(buscaUsuario))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(findByIdResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(findById))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(actualizarUsarioResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(actualizarUsario))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getUsers))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(updateUserResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(updateUser))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cerrarSesionResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cerrarSesion))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(iniciaSesionResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(iniciaSesion))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(darDeBajaUsuarioResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(darDeBajaUsuario))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(buscaUsuarioPassResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(buscaUsuarioPass))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(crearUsuarioResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(crearUsuario))]
public partial class EJBUserServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback crearUsuarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback buscaUsuarioPassOperationCompleted;
    
    private System.Threading.SendOrPostCallback darDeBajaUsuarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback iniciaSesionOperationCompleted;
    
    private System.Threading.SendOrPostCallback cerrarSesionOperationCompleted;
    
    private System.Threading.SendOrPostCallback updateUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback getUsersOperationCompleted;
    
    private System.Threading.SendOrPostCallback actualizarUsarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback findByIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback buscaUsuarioOperationCompleted;
    
    /// <remarks/>
    public EJBUserServiceService() {
        this.Url = "http://Vodkaneitor:8280/sdi3-40.EJB/UserService";
    }
    
    /// <remarks/>
    public event crearUsuarioCompletedEventHandler crearUsuarioCompleted;
    
    /// <remarks/>
    public event buscaUsuarioPassCompletedEventHandler buscaUsuarioPassCompleted;
    
    /// <remarks/>
    public event darDeBajaUsuarioCompletedEventHandler darDeBajaUsuarioCompleted;
    
    /// <remarks/>
    public event iniciaSesionCompletedEventHandler iniciaSesionCompleted;
    
    /// <remarks/>
    public event cerrarSesionCompletedEventHandler cerrarSesionCompleted;
    
    /// <remarks/>
    public event updateUserCompletedEventHandler updateUserCompleted;
    
    /// <remarks/>
    public event getUsersCompletedEventHandler getUsersCompleted;
    
    /// <remarks/>
    public event actualizarUsarioCompletedEventHandler actualizarUsarioCompleted;
    
    /// <remarks/>
    public event findByIdCompletedEventHandler findByIdCompleted;
    
    /// <remarks/>
    public event buscaUsuarioCompletedEventHandler buscaUsuarioCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void crearUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        this.Invoke("crearUsuario", new object[] {
                    arg0,
                    arg1});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincrearUsuario(user arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("crearUsuario", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndcrearUsuario(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void crearUsuarioAsync(user arg0, string arg1) {
        this.crearUsuarioAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void crearUsuarioAsync(user arg0, string arg1, object userState) {
        if ((this.crearUsuarioOperationCompleted == null)) {
            this.crearUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearUsuarioOperationCompleted);
        }
        this.InvokeAsync("crearUsuario", new object[] {
                    arg0,
                    arg1}, this.crearUsuarioOperationCompleted, userState);
    }
    
    private void OncrearUsuarioOperationCompleted(object arg) {
        if ((this.crearUsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.crearUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user buscaUsuarioPass([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        object[] results = this.Invoke("buscaUsuarioPass", new object[] {
                    arg0,
                    arg1});
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuscaUsuarioPass(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buscaUsuarioPass", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public user EndbuscaUsuarioPass(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public void buscaUsuarioPassAsync(string arg0, string arg1) {
        this.buscaUsuarioPassAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void buscaUsuarioPassAsync(string arg0, string arg1, object userState) {
        if ((this.buscaUsuarioPassOperationCompleted == null)) {
            this.buscaUsuarioPassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaUsuarioPassOperationCompleted);
        }
        this.InvokeAsync("buscaUsuarioPass", new object[] {
                    arg0,
                    arg1}, this.buscaUsuarioPassOperationCompleted, userState);
    }
    
    private void OnbuscaUsuarioPassOperationCompleted(object arg) {
        if ((this.buscaUsuarioPassCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buscaUsuarioPassCompleted(this, new buscaUsuarioPassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool darDeBajaUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("darDeBajaUsuario", new object[] {
                    arg0,
                    arg0Specified});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindarDeBajaUsuario(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("darDeBajaUsuario", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EnddarDeBajaUsuario(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void darDeBajaUsuarioAsync(long arg0, bool arg0Specified) {
        this.darDeBajaUsuarioAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void darDeBajaUsuarioAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.darDeBajaUsuarioOperationCompleted == null)) {
            this.darDeBajaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OndarDeBajaUsuarioOperationCompleted);
        }
        this.InvokeAsync("darDeBajaUsuario", new object[] {
                    arg0,
                    arg0Specified}, this.darDeBajaUsuarioOperationCompleted, userState);
    }
    
    private void OndarDeBajaUsuarioOperationCompleted(object arg) {
        if ((this.darDeBajaUsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.darDeBajaUsuarioCompleted(this, new darDeBajaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void iniciaSesion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg0, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] iniciaSesionEntry[] arg1) {
        this.Invoke("iniciaSesion", new object[] {
                    arg0,
                    arg1});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegininiciaSesion(user arg0, iniciaSesionEntry[] arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("iniciaSesion", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndiniciaSesion(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void iniciaSesionAsync(user arg0, iniciaSesionEntry[] arg1) {
        this.iniciaSesionAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void iniciaSesionAsync(user arg0, iniciaSesionEntry[] arg1, object userState) {
        if ((this.iniciaSesionOperationCompleted == null)) {
            this.iniciaSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OniniciaSesionOperationCompleted);
        }
        this.InvokeAsync("iniciaSesion", new object[] {
                    arg0,
                    arg1}, this.iniciaSesionOperationCompleted, userState);
    }
    
    private void OniniciaSesionOperationCompleted(object arg) {
        if ((this.iniciaSesionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.iniciaSesionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void cerrarSesion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg0, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] cerrarSesionEntry[] arg1) {
        this.Invoke("cerrarSesion", new object[] {
                    arg0,
                    arg1});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincerrarSesion(user arg0, cerrarSesionEntry[] arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("cerrarSesion", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndcerrarSesion(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void cerrarSesionAsync(user arg0, cerrarSesionEntry[] arg1) {
        this.cerrarSesionAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void cerrarSesionAsync(user arg0, cerrarSesionEntry[] arg1, object userState) {
        if ((this.cerrarSesionOperationCompleted == null)) {
            this.cerrarSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncerrarSesionOperationCompleted);
        }
        this.InvokeAsync("cerrarSesion", new object[] {
                    arg0,
                    arg1}, this.cerrarSesionOperationCompleted, userState);
    }
    
    private void OncerrarSesionOperationCompleted(object arg) {
        if ((this.cerrarSesionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.cerrarSesionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void updateUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg0) {
        this.Invoke("updateUser", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginupdateUser(user arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("updateUser", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndupdateUser(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void updateUserAsync(user arg0) {
        this.updateUserAsync(arg0, null);
    }
    
    /// <remarks/>
    public void updateUserAsync(user arg0, object userState) {
        if ((this.updateUserOperationCompleted == null)) {
            this.updateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateUserOperationCompleted);
        }
        this.InvokeAsync("updateUser", new object[] {
                    arg0}, this.updateUserOperationCompleted, userState);
    }
    
    private void OnupdateUserOperationCompleted(object arg) {
        if ((this.updateUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.updateUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user[] getUsers() {
        object[] results = this.Invoke("getUsers", new object[0]);
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetUsers(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getUsers", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public user[] EndgetUsers(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public void getUsersAsync() {
        this.getUsersAsync(null);
    }
    
    /// <remarks/>
    public void getUsersAsync(object userState) {
        if ((this.getUsersOperationCompleted == null)) {
            this.getUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUsersOperationCompleted);
        }
        this.InvokeAsync("getUsers", new object[0], this.getUsersOperationCompleted, userState);
    }
    
    private void OngetUsersOperationCompleted(object arg) {
        if ((this.getUsersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getUsersCompleted(this, new getUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void actualizarUsario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg0) {
        this.Invoke("actualizarUsario", new object[] {
                    arg0});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginactualizarUsario(user arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("actualizarUsario", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndactualizarUsario(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void actualizarUsarioAsync(user arg0) {
        this.actualizarUsarioAsync(arg0, null);
    }
    
    /// <remarks/>
    public void actualizarUsarioAsync(user arg0, object userState) {
        if ((this.actualizarUsarioOperationCompleted == null)) {
            this.actualizarUsarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarUsarioOperationCompleted);
        }
        this.InvokeAsync("actualizarUsario", new object[] {
                    arg0}, this.actualizarUsarioOperationCompleted, userState);
    }
    
    private void OnactualizarUsarioOperationCompleted(object arg) {
        if ((this.actualizarUsarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.actualizarUsarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user findById([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0) {
        object[] results = this.Invoke("findById", new object[] {
                    arg0});
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindById(long arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findById", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public user EndfindById(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public void findByIdAsync(long arg0) {
        this.findByIdAsync(arg0, null);
    }
    
    /// <remarks/>
    public void findByIdAsync(long arg0, object userState) {
        if ((this.findByIdOperationCompleted == null)) {
            this.findByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByIdOperationCompleted);
        }
        this.InvokeAsync("findById", new object[] {
                    arg0}, this.findByIdOperationCompleted, userState);
    }
    
    private void OnfindByIdOperationCompleted(object arg) {
        if ((this.findByIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findByIdCompleted(this, new findByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.uo/", ResponseNamespace="http://impl.business.sdi.uo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user buscaUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
        object[] results = this.Invoke("buscaUsuario", new object[] {
                    arg0});
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuscaUsuario(string arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buscaUsuario", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public user EndbuscaUsuario(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user)(results[0]));
    }
    
    /// <remarks/>
    public void buscaUsuarioAsync(string arg0) {
        this.buscaUsuarioAsync(arg0, null);
    }
    
    /// <remarks/>
    public void buscaUsuarioAsync(string arg0, object userState) {
        if ((this.buscaUsuarioOperationCompleted == null)) {
            this.buscaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaUsuarioOperationCompleted);
        }
        this.InvokeAsync("buscaUsuario", new object[] {
                    arg0}, this.buscaUsuarioOperationCompleted, userState);
    }
    
    private void OnbuscaUsuarioOperationCompleted(object arg) {
        if ((this.buscaUsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buscaUsuarioCompleted(this, new buscaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class user {
    
    private string emailField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private string loginField;
    
    private string nameField;
    
    private string passwordField;
    
    private userStatus statusField;
    
    private bool statusFieldSpecified;
    
    private string surnameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public userStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public enum userStatus {
    
    /// <remarks/>
    ACTIVE,
    
    /// <remarks/>
    CANCELLED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class Exception {
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class buscaUsuarioResponse {
    
    private user returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class buscaUsuario {
    
    private string arg0Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class findByIdResponse {
    
    private user returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class findById {
    
    private long arg0Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class actualizarUsarioResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class actualizarUsario {
    
    private user arg0Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class getUsers {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class updateUserResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class updateUser {
    
    private user arg0Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class cerrarSesionResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class cerrarSesion {
    
    private user arg0Field;
    
    private cerrarSesionEntry[] arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public cerrarSesionEntry[] arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://impl.business.sdi.uo/")]
public partial class cerrarSesionEntry {
    
    private string keyField;
    
    private object valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class iniciaSesionResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class iniciaSesion {
    
    private user arg0Field;
    
    private iniciaSesionEntry[] arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public iniciaSesionEntry[] arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://impl.business.sdi.uo/")]
public partial class iniciaSesionEntry {
    
    private string keyField;
    
    private object valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class darDeBajaUsuarioResponse {
    
    private bool returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class darDeBajaUsuario {
    
    private long arg0Field;
    
    private bool arg0FieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool arg0Specified {
        get {
            return this.arg0FieldSpecified;
        }
        set {
            this.arg0FieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class buscaUsuarioPassResponse {
    
    private user returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class buscaUsuarioPass {
    
    private string arg0Field;
    
    private string arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class crearUsuarioResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.uo/")]
public partial class crearUsuario {
    
    private user arg0Field;
    
    private string arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void crearUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void buscaUsuarioPassCompletedEventHandler(object sender, buscaUsuarioPassCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buscaUsuarioPassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buscaUsuarioPassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void darDeBajaUsuarioCompletedEventHandler(object sender, darDeBajaUsuarioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class darDeBajaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal darDeBajaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void iniciaSesionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void cerrarSesionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void updateUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void getUsersCompletedEventHandler(object sender, getUsersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void actualizarUsarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void findByIdCompletedEventHandler(object sender, findByIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void buscaUsuarioCompletedEventHandler(object sender, buscaUsuarioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buscaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buscaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user)(this.results[0]));
        }
    }
}
